apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: my-bucket-WsKlpERP37iO  # CHANGE THIS to something unique!
spec:
  forProvider:
    region: ap-south-1
  providerConfigRef:
    name: default
